// Generated by gencpp from file roboclaw_driver/Stats.msg
// DO NOT EDIT!


#ifndef ROBOCLAW_DRIVER_MESSAGE_STATS_H
#define ROBOCLAW_DRIVER_MESSAGE_STATS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboclaw_driver
{
template <class ContainerAllocator>
struct Stats_
{
  typedef Stats_<ContainerAllocator> Type;

  Stats_()
    : header()
    , m1_enc_val(0)
    , m2_enc_val(0)
    , m1_enc_qpps(0)
    , m2_enc_qpps(0)  {
    }
  Stats_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , m1_enc_val(0)
    , m2_enc_val(0)
    , m1_enc_qpps(0)
    , m2_enc_qpps(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _m1_enc_val_type;
  _m1_enc_val_type m1_enc_val;

   typedef int32_t _m2_enc_val_type;
  _m2_enc_val_type m2_enc_val;

   typedef int32_t _m1_enc_qpps_type;
  _m1_enc_qpps_type m1_enc_qpps;

   typedef int32_t _m2_enc_qpps_type;
  _m2_enc_qpps_type m2_enc_qpps;





  typedef boost::shared_ptr< ::roboclaw_driver::Stats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboclaw_driver::Stats_<ContainerAllocator> const> ConstPtr;

}; // struct Stats_

typedef ::roboclaw_driver::Stats_<std::allocator<void> > Stats;

typedef boost::shared_ptr< ::roboclaw_driver::Stats > StatsPtr;
typedef boost::shared_ptr< ::roboclaw_driver::Stats const> StatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboclaw_driver::Stats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboclaw_driver::Stats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboclaw_driver::Stats_<ContainerAllocator1> & lhs, const ::roboclaw_driver::Stats_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.m1_enc_val == rhs.m1_enc_val &&
    lhs.m2_enc_val == rhs.m2_enc_val &&
    lhs.m1_enc_qpps == rhs.m1_enc_qpps &&
    lhs.m2_enc_qpps == rhs.m2_enc_qpps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboclaw_driver::Stats_<ContainerAllocator1> & lhs, const ::roboclaw_driver::Stats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboclaw_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roboclaw_driver::Stats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboclaw_driver::Stats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboclaw_driver::Stats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboclaw_driver::Stats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboclaw_driver::Stats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboclaw_driver::Stats_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboclaw_driver::Stats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "210b25d19a34293aed84261a946d88a5";
  }

  static const char* value(const ::roboclaw_driver::Stats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x210b25d19a34293aULL;
  static const uint64_t static_value2 = 0xed84261a946d88a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboclaw_driver::Stats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboclaw_driver/Stats";
  }

  static const char* value(const ::roboclaw_driver::Stats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboclaw_driver::Stats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# std_msgs/Header \n"
"Header header\n"
"\n"
"# Motor 1 & 2 encoder values\n"
"int32 m1_enc_val\n"
"int32 m2_enc_val\n"
"\n"
"# Motor 1 & 2 speed values in QPPS (+/-)\n"
"int32 m1_enc_qpps\n"
"int32 m2_enc_qpps\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::roboclaw_driver::Stats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboclaw_driver::Stats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.m1_enc_val);
      stream.next(m.m2_enc_val);
      stream.next(m.m1_enc_qpps);
      stream.next(m.m2_enc_qpps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboclaw_driver::Stats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboclaw_driver::Stats_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "m1_enc_val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m1_enc_val);
    s << indent << "m2_enc_val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m2_enc_val);
    s << indent << "m1_enc_qpps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m1_enc_qpps);
    s << indent << "m2_enc_qpps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m2_enc_qpps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCLAW_DRIVER_MESSAGE_STATS_H
