# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboclaw_driver/SpeedCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SpeedCommand(genpy.Message):
  _md5sum = "1217b4f680d01eb5008f99442806c05f"
  _type = "roboclaw_driver/SpeedCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Motor speed in QPPS
int32 m1_qpps
int32 m2_qpps

# Acceleration
uint32 accel

# Max seconds before automatically stopping
uint32 max_secs
"""
  __slots__ = ['m1_qpps','m2_qpps','accel','max_secs']
  _slot_types = ['int32','int32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       m1_qpps,m2_qpps,accel,max_secs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SpeedCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.m1_qpps is None:
        self.m1_qpps = 0
      if self.m2_qpps is None:
        self.m2_qpps = 0
      if self.accel is None:
        self.accel = 0
      if self.max_secs is None:
        self.max_secs = 0
    else:
      self.m1_qpps = 0
      self.m2_qpps = 0
      self.accel = 0
      self.max_secs = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i2I().pack(_x.m1_qpps, _x.m2_qpps, _x.accel, _x.max_secs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.m1_qpps, _x.m2_qpps, _x.accel, _x.max_secs,) = _get_struct_2i2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i2I().pack(_x.m1_qpps, _x.m2_qpps, _x.accel, _x.max_secs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.m1_qpps, _x.m2_qpps, _x.accel, _x.max_secs,) = _get_struct_2i2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i2I = None
def _get_struct_2i2I():
    global _struct_2i2I
    if _struct_2i2I is None:
        _struct_2i2I = struct.Struct("<2i2I")
    return _struct_2i2I
